# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-28 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180727_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='lessons_id',
            new_name='lessons',
        ),
        migrations.RenameField(
            model_name='scorestudent',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='scorestudent',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='last_course_id',
            new_name='last_course',
        ),
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
    ]
