# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180728_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='number',
        ),
        migrations.AlterField(
            model_name='courses',
            name='next_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nextOne', to='api.Courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='previous_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previousOne', to='api.Courses'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='next_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nextOne', to='api.Lessons'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='previous_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previousOne', to='api.Lessons'),
        ),
    ]
