# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-29 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180729_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorestudent',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Lessons'),
        ),
    ]
