# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-29 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_scorestudent_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogScoreStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Courses')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Lessons')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Students')),
            ],
            options={
                'db_table': 'LogScoreStudent',
                'managed': True,
            },
        ),
    ]
