# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-29 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180729_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogQuestionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Questions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Users')),
            ],
            options={
                'db_table': 'log_questions_user',
                'managed': True,
            },
        ),
        migrations.AlterModelTable(
            name='scorestudent',
            table='score_student',
        ),
    ]
