# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-29 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180729_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logquestionuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Students'),
        ),
    ]
