# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-29 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180729_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='logquestionuser',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Lessons'),
        ),
        migrations.AlterModelTable(
            name='logscorestudent',
            table='log_score_student',
        ),
    ]
